CARTPOLE = dict(
    gym_name='CartPole-v1',
    algo="ppo",
    policy_episodes=500,
    experiment_episodes=100,
    k_bins=1,
    train=False,
    run_experiment=True,
    abstraction=True,
    load_model=True,
    render_policy=False,
    render_experiment=False)

LUNAR_LANDER = dict(
    gym_name='LunarLander-v2',
    algo="ppo",
    policy_episodes=2000,
    experiment_episodes=200,
    k_bins=1,
    train=False,
    run_experiment=True,
    abstraction=True,
    load_model=True,
    render_policy=False,
    render_experiment=False)

ACROBOT = dict(
    gym_name='Acrobot-v1',
    algo="ppo",
    policy_episodes=1000,
    experiment_episodes=200,
    k_bins=1,
    train=False,
    run_experiment=True,
    abstraction=True,
    load_model=False,
    render_policy=False,
    render_experiment=False)

MOUNTAIN_CAR = dict(
    gym_name='MountainCar-v0',
    algo="ppo",
    policy_episodes=1000,
    experiment_episodes=200,
    k_bins=1,
    train=True,
    run_experiment=True,
    abstraction=True,
    load_model=False,
    render_policy=False,
    render_experiment=False)

PENDULUM = dict(
    gym_name='Pendulum-v1',
    algo="ppo",
    policy_episodes=1000,
    experiment_episodes=200,
    k_bins=20,
    train=False,
    run_experiment=True,
    abstraction=True,
    load_model=False,
    render_policy=False,
    render_experiment=False)

MOUNTAIN_CAR_CONTINUOUS = dict(
    gym_name='MountainCarContinuous-v0',
    algo="ppo",
    policy_episodes=2000,
    experiment_episodes=200,
    k_bins=20,
    train=True,
    run_experiment=True,
    abstraction=True,
    load_model=False,
    render_policy=False,
    render_experiment=False)
